language: python
env:
- DATABASE_URL='postgres://postgres:@localhost:5432/vms' DOWNLOAD='False'
python:
- '3.6'
services:
- postgresql
install:
- pip install -q -r web/requirements.txt
before_script:
- cd ./web
- psql -c 'create database vms;' -U postgres
- python manage.py makemigrations --noinput
- python manage.py migrate --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ibvvE+IdKJiqMChJST+fx2+QQgWwpe311+o9j0JKUbQSQYTqNory8ITKIOzS6nramFT7INfcHrmc4hityRijcc5kLCW4i2ks+lBEeSmBtddGZlFhMx3+c/8s0o1JP/gQOLUVWTcoJB9vfGdn50mnCrZefU0KtfHmaFi19mTSFjSpfNxzgSR7q6sPXZxGIhKe2c5dPphypRUYp6MRTlZEYr7PCQ6DAkLWSTweVN6THokmbwD6aY6RBCJ7UTqUkRyqkNtJXlu5cmP7GV9n6wN+tHiBVScuhkn3t73VRtwRc26neqPCpCTyTwDAp/LCTb9MSLenC+T3JPi8PbP7bea4aYTBR70y55cy8X/6EJxixzlDV8P2ayixpiKw9sgjbWmK3p0DqvyJY7cte41BiNzhYnKVL1jfp6gE9VFQjxqOT7W9XXabntRlNij3yUUWBaSmoWhcqzSdGasWjsuZlWf8hrX1qB4gKkYXRzfIz8T12E7u/3Sk3pEzsUvuy2EFN7l3oTK2Ym3aMpgb18J7MtJTSYCPyLoEnxLlC0C7sBPHZz2OlQEHDUbBfS4zvcLxJ6kIeYdDCMhiPHi6QS5xGoqdF7ZsYy2PZLwR2sgW8D6IicBumFAGTcOipQyGkOU3G07KwU8HY0M0wDWatDZRqW0ZuqVFKUMi5KuS4n8n0Fr0fG8=
  app: vms-techm
  on:
    repo: rajeevrmenon97/vms
