language: python
env:
- DATABASE_URL='mysql://root:@localhost:3306/vms"
python:
- '3.6'
services:
- mysql
install:
- pip install -q -r requirements.txt
before_script:
- mysql -u root -e 'CREATE DATABASE vms;'
- python manage.py makemigrations --noinput
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: G9Ka5MrC8c9uJIOEHI4h7grCSqvLFmzt83NujhiKNOyHq4Hq3stBrYNBws2SovvZHP3j3VP4r7/G7RYAwcpyG2dJaT+KX84TVs9jz4UJOp6RYVem3r0UveUrVdlkEQiJsC1x4Y1xpDeUB5QEXWSQK0u+ygwyNKg1i2UyMnoUix4Y1bo0H9VbuZj4ZHYDIN6d3D142QsM/FEkbWYKH4np2z7FVCCjUFPd9FAjLsIq+iFWB+ios8Qp9/xZ3JwZ5DFTjf9KbLEh7sc1f9vfLYTaHu/tlYqUN1fpBErSjuOCzZRwBcnTXKegjRP6dvcZb35cTaaXtPxej+Gt1z+2S0lI50qoFlzjgDijUc9MqXkthzocZrqPT9EAYsyW99fnuRqOhz1qDeGg3JHVMX0bxRFceRTXxmfBtdNQte8P6s9e8ich8QdNMPQyyrBlhrh8M178IaaLhEEnpbFoWqq5BWwQNvuoDBC0xuFoVqzmVaFVR7Swc78J7U308L+p/2w7qALU8k0glk+aFeifvTsUVHd3/EFy1hlvFSscBrChMb7J46IwZZz2luyRjFlKF4fO8pnwhtjr1nZv5SC9j/K6gOQJ9Yw7yYFrBE/Fc/Yq/87q7KM3a+rpcHrJPV7t029XkuXDFELDnbHy2kRW2m5/mqibs4dHphOO4ifIgGEAfI7euA8=
  app: vms-techm
  on:
    repo: rajeevrmenon97/vms
