language: python
env:
- DATABASE_URL='mysql://root:@localhost:3306/vms'
python:
- '3.6'
services:
- mysql
install:
- pip install -q -r requirements.txt
before_script:
- mysql -u root -e 'CREATE DATABASE vms;'
- python manage.py makemigrations --noinput
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: qHq6KhBSw/qYFc0uhbseClRTU8nYBM0k2lGVqwNb9uEvB9XGI7ujbwNewKYcUEEMhQNnEzkZ5scLTIxKkT6hewHRY3SALvWLVkw+xPYd6ImEhG1DWw7piJp71+l9/cVwNcKE+dT6BJ4Ilra1Yi1QxqThOvUb/VOVAX3X6z63fwT4nVymDJQqBpfRwJCCufc1wz/ZM8vkA+DIvcX7vuVudbFYzExmK/lEKQdfWOvnQIwqP2XqD3czrgv/8jPiISaln3PO4jHcpkANZDUcr/YFGvor7f+T+j7ByQpa4rjnSrCQ9zGQZW7A6LqVfCfhYkssI5Gi1txWCOC4mlTeNw3OJMHL/r25GoPYeaPwq89Rr/NAwbLshih6pjN3sq+C91/JOrOafEsytuHr+eoFdecR6D5b7KpPlO+wZ/5zWWFXMfBpXTNqaUJlfVcdZzRpyV0SfLA56dqF9pxFcmFkENRHtg786CH8lOC9PIuR+OwTryPi7h7WzzN56M5o8dEo+5OaiIrvS2EU9bM6GICt5r0NdQkvG6znXvOrPWWwiqoha0Ptxj/tCGQozj8LOLpKJmPLeipBabhnLShnAygc0mnJGC/wjxcFqWdYqeHSe0dkekJ4/113UXDhxSvZ5yriA4eMzvydaBp3ISxB7lzWXzsHNwe+tqwDXaOhnT3BdJQYeV0=
  app: vms-techm
  on:
    repo: rajeevrmenon97/vms
