version: '2'

services:

  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres
      - redis
      - elasticsearch
      - kibana
    env_file:
      - ./env
      - ./proxy
    volumes:
      - ./web:/data/web
    command: /usr/bin/gunicorn vms.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - postgres_data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - ./env
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  postgres_data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"

  celery:
    build: ./celery/
    command: /celery_start.sh
    volumes_from:
      - web
    links:
      - postgres
      - redis
      - elasticsearch
    env_file:
      - ./env
      - ./proxy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch

volumes:
  esdata:
    driver: local
